routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Notifications\Newinfo;
use App\Notifications\Newslack;

Route::get('/slack', function () {



$user = App\User::first();



$user->notify(new Newslack());



   echo "Juste une notif de oschool paths";



});

Route::get('/email', function () {

$user = App\User::first();

$user->notify(new Newinfo("A new user has visited on your application."));

   return view('homepage');

})->name('email');



Route::get('/import', 'ImportController@getImport')->name('import');
Route::post('/import_parse', 'ImportController@parseImport')->name('import_parse');
Route::post('/import_process', 'ImportController@processImport')->name('import_process');


Route::get('/', 'HomeController@racine')->name('accueil');

Route::get('/paypalstatus', 'HomeController@dashboard');



/*route pour la recherche avec ajax des users*/

Route::get('/live_search', 'LiveSearch@index');
Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');


Route::post('/merci', function () {
    return view('merci');
});

Route::post('paypal', 'PaymentController@payWithpaypal')->name('payWithpaypal');
Route::get('status', 'PaymentController@getPaymentStatus')->name('status');



Route::get('/castaing', function () {
    return view('formations.template-castaing');
});

Route::get('/cefiat', function () {
    return view('formations.template-cefiat');
});

Route::get('/esma', function () {
    return view('formations.template-esma');
});

Route::get('/etep', function () {
    return view('formations.template-etep');
});

Route::get('/epcci', function () {
    return view('formations.template-epcci');
});

Route::get('/esatic', function () {
    return view('formations.template-esatic');
});

Route::get('/ensit', function () {
    return view('formations.template-ensit');
});






Route::get('/online', function () {
    return view('online');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
Route::get('register', function () {
    return view('accueil');
});  */


Route::get('/classrooms', 'HomeController@classrooms');

Route::get('/default', 'UserController@default');

Route::get('/admin', 'AdminController@admin')
    ->middleware('is_admin')
    ->name('admin');

Route::get('/teacher', 'TeacherController@teacher')
    ->middleware('is_teacher')
    ->name('teacher');

Route::get('/partner', 'PartnerController@partner')
    ->middleware('is_partner')
    ->name('partner');


Route::resource('users','UserController');

Route::resource('emails','EmailController');

Route::resource('etatprogressions','EtatprogressionController');

Route::resource('classrooms','ClassroomController');

Route::resource('progressions','ProgressionController');

Route::resource('achats','AchatController');

Route::resource('offers','OfferController');

Route::resource('characteristics','CharacteristicController');

Route::post('/envoi', 'AchatController@envoi')->name('envoi');

Route::post('/envoiRenew', 'AchatController@envoiRenew');

Route::post('renew', 'AchatController@renew');

Route::post('/progression', 'ProgressionController@progression')->name('progression');

Route::post('/formation', 'FormationController@formation')->name('formation');

Route::post('/notify', 'AchatController@notify')->name('notify');

/*
route pour les sessions ou classrooms
*/

Route::get('/valider/{etatprogression}', 'EtatprogressionController@valider')->name('valider');

Route::get('/programme', 'ProgressionController@programme')->name('programme');

Route::get('/progression/{user}', 'ProgressionController@voir')->name('progression');

Route::resource('formations','FormationController');

Route::get('/formation/{slug}', 'FormationController@showSlug')->name('formation.slug');

Route::get('/category/{slug}', 'CategoryController@showSlug')->name('category.slug');

Route::resource('partners','PartnerController');

Route::resource('languages','LanguageController');

Route::resource('prerequisites','PrerequisiteController');

Route::resource('categories','CategoryController');

Route::resource('guides','GuideController');

Route::resource('guideprojets','GuideprojetController');

Route::get('/projects/{formation}', 'FormationController@projects')->name('projects');

Route::post('/inscription', 'UserController@inscription')->name('inscription');

Route::get('/inscrire/{user}', 'UserController@inscrire')->name('inscrire');

Route::get('/mes-etudiants', 'UserController@mesEtudiants')->name('mes-etudiants');

Route::get('/devweb', function () {
    return view('formations.parcours-dev-web');
})->name('devweb');

Route::get('/devweb2', function () {
    return view('formations.parcours-dev-web2');
})->name('devweb2');

Route::get('/facebook-marketing', function () {
    return view('formations.parcours-facebook-marketing');
})->name('facebook-marketing');

Route::get('/webdesign', function () {
    return view('formations.web-design');
})->name('web-design');

Route::get('/trading', function () {
    return view('formations.trading');
})->name('trading');

Route::get('/frontend', function () {
    return view('formations.front-end');
})->name('front-end');

Route::get('/devmobile', function () {
    return view('formations.dev-mobile');
})->name('dev-mobile');

Route::get('/devmobile', function () {
    return view('formations.dev-mobile');
})->name('dev-mobile');

Route::get('/community-management', function () {
    return view('formations.parcours-community-management');
})->name('community-management');

Route::get('/blog', function () {
    return view('formations.blog');
})->name('blog');

Route::get('/jeuxvideos', function () {
    return view('formations.parcours-jv');
})->name('jeux-videos');

Route::get('/android', function () {
    return view('formations.parcours-android');
})->name('android');

Route::get('/after-effects', function () {
    return view('formations.after-effects');
})->name('android');
Route::get('/anglais', function () {
    return view('formations.parcours-anglais');
})->name('anglais');

Route::get('/photoshop', function () {
    return view('formations.parcours-photoshop');
})->name('photoshop');

Route::get('/after-effects', function () {
    return view('formations.parcours-after-effects');
})->name('photoshop');

Route::get('/kali-linux', function () {
    return view('formations.parcours-kali-linux');
})->name('kali-linux');

Route::get('/python', function () {
    return view('formations.python');
})->name('python');

Route::get('/cours', function () {
    return view('formations.cours');
})->name('cours');

Route::get('/ecoleprog', function () {
    return view('formations.ecoleprog');
});

Route::get('/ecolemarketing', function () {
    return view('formations.ecolemarketing');
});

Route::get('/ecolelang', function () {
    return view('formations.ecolelang');
});

Route::get('/ecolebusiness', function () {
    return view('formations.ecolebusiness');
});

Route::get('/ecoleai', function () {
    return view('formations.ecoleai');
});

Route::get('/ecoledatascience', function () {
    return view('formations.ecoledatascience');
});

//voir facturation pour les teachers

Route::get('/factures', 'UserController@factures');

Route::post('/moisFactures', 'UserController@moisFactures');

Route::get('/settings', 'UserController@settings');

//voir facturation pour les admins

Route::get('/paiements', 'UserController@paiements')->name('paiements');

Route::post('/moisPaiements', 'UserController@moisPaiements');

Route::post('/formationpaiement', 'FormationController@formationpaiement')->name('paiement-par-formation');

//voir les sessions mensuelles des profs pour les admins

Route::get('/rapportProf', 'UserController@rapportProf');

Route::post('/rapportMoisProf', 'UserController@rapportMoisProf');


Route::get('/documentsTeacher', 'UserController@documentsTeacher')->name('documentsTeacher');

Route::get('/documentsStudent', 'UserController@documentsStudent')->name('documentsStudent');

Route::resource('projets','ProjetController');

Route::resource('etatprojets','EtatprojetController');

Route::resource('supportformations','SupportformationController');

Route::resource('achats','AchatController');

Route::post('/ajout-achat', 'AchatController@achat')->name('ajout-achat');

/* pour les entreprises*/

Route::get('/entreprise', function () {
    return view('formations.entreprise');
});

Route::get('/entreprise2', function () {
    return view('formations.entreprise2');
});


//pour retrouver la page profil user

Route::get('/dashboard-teacher', 'HomeController@dashboardT')->name('dashboard');

Route::get('/dashboard-admin', 'HomeController@dashboardA')->name('dashboard');

Route::get('/dashboard-default', 'HomeController@dashboard')->name('dashboard');

//pour mettre à jour le statut des abonnés

Route::get('/statutCheck', 'UserController@statutCheck')->name('statutCheck');

app/Classroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Classroom extends Model
{
  //on crée les champs qui seront dans la table classroom
  protected $fillable = ['date', 'etudiant', 'formateur', 'user_id', 'commentaire', 'idEtudiant', 'statut'];

  //Relation one-to-many : ici, une classe a un seul teacher

  public function teacher()
  {
      return $this->belongsTo('App\User');
  }
}

app/Http/Controllers/ClassroomController.php
<?php

namespace App\Http\Controllers;

use App\Classroom;
use App\User;
use Auth;
use Illuminate\Http\Request;
use Mail;

class ClassroomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      if (Auth::check() && Auth::user()->type2 !== "teacher" && count(Auth::user()->formations)) {
          $classrooms = Classroom::where('etudiant', Auth::user()->name)->orderby('date', 'desc')->paginate(30);
          return view('classrooms.index', ['classrooms' => $classrooms]);
        }
      elseif (Auth::check() && Auth::user()->type2 == "teacher" && count(Auth::user()->formations)) {
          $classrooms = Classroom::where('formateur', Auth::user()->name)->orderby('date', 'desc')->paginate(30);
          return view('classrooms.index', ['classrooms' => $classrooms]);
        }
      else {
        return redirect('home');
      }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if (Auth::check() && Auth::user()->isTeacher()) {
          $students = Auth::user()->students()->where('statut', 'OK')->get();
          return view('classrooms.ajouter', ['students' => $students]);
        }
        else {
          return redirect('home');
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $classroom = Classroom::create($request->all());

      $user = User::find($request['idEtudiant']);

      //envoi mail étudiant
      Mail::send('mails.planification-session', ['classroom' => $classroom, 'user' => $user], function($message) use ($user){
        $message->to($user->email, 'Cher(ère) Etudiant(e)')->subject('Une nouvelle séance de formation a été programmée pour toi');
        $message->from('eventsoschool@gmail.com', 'Oschool');
      });

      //envoi mail teacher
      Mail::send('mailsTeacher.planification-session', ['classroom' => $classroom], function($message) use ($classroom){
        $message->to(Auth::user()->email, 'A '.Auth::user()->name)->subject('Vous venez de programmer une nouvelle séance de formation');
        $message->from('eventsoschool@gmail.com', 'Oschool');
      });

      return redirect('classrooms')->with('status', 'La session a bien été créée.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Classroom  $classroom
     * @return \Illuminate\Http\Response
     */
    public function show(Classroom $classroom)
    {
        //
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Classroom  $classroom
     * @return \Illuminate\Http\Response
     */
    public function edit(Classroom $classroom)
    {
        return view('classrooms.edit', ['classroom' => $classroom]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Classroom  $classroom
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Classroom $classroom)
    {
        $classroom->update($request->all());

        $detail=$request->commentaire;

        $dom = new \domdocument();
        $dom->loadHtml($detail, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);

        $images = $dom->getelementsbytagname('img');

        foreach($images as $k => $img){
            $data = $img->getattribute('src');

            list($type, $data) = explode(';', $data);
            list(, $data)      = explode(',', $data);

            $data = base64_decode($data);
            $image_name= time().$k.'.png';
            $path = public_path() .'/img/classrooms/'. $image_name;

            file_put_contents($path, $data);

            $img->removeattribute('src');
            $img->setattribute('src', '/img/classrooms/'. $image_name);
        }

        $detail = $dom->savehtml();
        $classroom->commentaire = $detail;
        $classroom->save();
        return redirect('classrooms')->with('status', 'Vos informations ont bien été entregistrées !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Classroom  $classroom
     * @return \Illuminate\Http\Response
     */
    public function destroy(Classroom $classroom)
    {
        //
    }
}

resources/views/classrooms/ajouter.blade.php
<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>Parcours Oschool | Planifier une session</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
		<link rel="icon" type="image/png" href="/sessions/images/icons/image-profil.png"/>
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/fonts/iconic/css/material-design-iconic-font.min.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/vendor/animate/animate.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/vendor/noui/nouislider.min.css">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="/sessions/css/util.css">
		<link rel="stylesheet" type="text/css" href="/sessions/css/main.css">
	<!--===============================================================================================-->
	</head>
	<body>


		<div class="container-contact100">
			<div class="wrap-contact100">
				<img style="width: 40%;display: block;margin-left: auto;margin-right: auto;" src="/formcreate/images/img-01.png" alt="">
				<h2 style="margin: 25px 0px;">Planifier une session</h2>
				<form method="post" enctype="multipart/form-data" action="{{ route('classrooms.store') }}" class="contact100-form validate-form">
					{{ csrf_field() }}
          <div style="display: none;" class="wrap-input100 input100-select bg1">
						<span class="label-input100">Formateur</span>
						<div>
							<input type="text" name="formateur" value="{{Auth::user()->name}}">
						</div>
					</div>

          <div style="display: none;" class="wrap-input100 input100-select bg1">
						<span class="label-input100">User Id</span>
						<div>
							<input type="text" name="user_id" value="{{Auth::user()->id}}">
						</div>
					</div>


          <div class="wrap-input100 input100-select bg1">
						<span class="label-input100">Date</span>
                <div class="form-group has-warning has-feedback">
                <label for="inputWarning2">Selectionner la date ET l'heure</label>
                <input name="date" type="datetime-local" class="form-control" id="inputWarning2">
                <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
            </div>
					</div>


					<div class="wrap-input100 input100-select bg1">
						<span class="label-input100">Etudiant</span>
						<div>
							<select class="js-select3" name="etudiant">
                @foreach($students as $student)
							    <option value="{{ $student->name }}">{{ $student->name }}</option>
                @endforeach
							</select>
							<div class="dropDownSelect3"></div>
						</div>
					</div>

					<div class="wrap-input100 input100-select bg1">
						<span class="label-input100">Confirmer l'étudiant choisi</span>
						<div>
							<select class="js-select3" name="idEtudiant">
                @foreach($students as $student)
                  <option value="{{ $student->id }}">{{ $student->name }}</option>
                @endforeach
							</select>
							<div class="dropDownSelect3"></div>
						</div>
					</div>




					<div class="container-contact100-form-btn">
						<button class="contact100-form-btn">
							<span>
								Envoyer
								<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
							</span>
						</button>

						<p style="margin-top: 10px;"> <a href="{{url('home')}}">Retour au tableau de bord</a> </p>
					</div>
				</form>
			</div>
		</div>



	<!--===============================================================================================-->
		<script src="/sessions/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
		<script src="/sessions/vendor/animsition/js/animsition.min.js"></script>
	<!--===============================================================================================-->
		<script src="/sessions/vendor/bootstrap/js/popper.js"></script>
		<script src="/sessions/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
		<script src="/sessions/vendor/select2/select2.min.js"></script>

		<script>
		$(".js-select3").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect3')
			});
		})
		</script>

	<!--===============================================================================================-->
		<script src="/sessions/vendor/daterangepicker/moment.min.js"></script>
		<script src="/sessions/vendor/daterangepicker/daterangepicker.js"></script>
	<!--===============================================================================================-->
		<script src="/sessions/vendor/countdowntime/countdowntime.js"></script>
	<!--===============================================================================================-->
		<script src="/sessions/vendor/noui/nouislider.min.js"></script>

	</body>
</html>

resources/views/classrooms/create.blade.php
@extends('layouts.menu-login')
@section('title', 'Séance de cours Oschool')

@section('content')


<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
      <div class="login100-pic js-tilt" data-tilt>
        <img src="/formcreate/images/img-01.png" alt="IMG">
      </div>

      <form method="post" enctype="multipart/form-data" action="{{ route('classrooms.store') }}" class="login100-form validate-form">
        <span class="login100-form-title">
          Séance de formation
        </span>
        {{ csrf_field() }}

        <div class="wrap-input100 validate-input" data-validate = "Jour de la séance">
          <label for="">Jour de la séance</label>
          <input class="input100" type="date" name="date" placeholder="" required>
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-calendar" aria-hidden="true"></i>
          </span>
        </div>

        <div class="wrap-input100 validate-input" data-validate = "Etudiant">
          <label for="">Etudiant</label>
          <select name="etudiant" class="form-control" style="" required>
            @foreach(Auth::user()->students as $student)
            <option value="{{ $student->name }}">{{ $student->name }}</option>
            @endforeach
          </select>
        </div>

        <div class="wrap-input100 validate-input" data-validate = "Etudiant">
          <label for="">Confirmer l'étudiant</label>
          <select name="idEtudiant" class="form-control" style="" required>
            @foreach(Auth::user()->students as $student)
            <option value="{{ $student->id }}">{{ $student->name }}</option>
            @endforeach
          </select>
        </div>

        <div style="display: none;" class="wrap-input100 validate-input">
          <input class="input100" value="{{Auth::user()->name}}" type="text" name="formateur" placeholder="">
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-user" aria-hidden="true"></i>
          </span>
        </div>

        <div style="display: none;" class="wrap-input100 validate-input">
          <input class="input100" value="{{Auth::user()->id}}" type="text" name="user_id" placeholder="">
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-user" aria-hidden="true"></i>
          </span>
        </div>

        <div class="wrap-input100 validate-input">
          <textarea placeholder="Commentaire de la session" rows="50" style="height: 300px;" class="input100" name="commentaire" placeholder=""></textarea>
        </div>

        <div class="container-login100-form-btn">
          <button class="login100-form-btn">
            Ajouter la séance
          </button>
        </div>


        <div class="text-center p-t-136">
          <a class="txt2" href="{{url('home')}}">
            Allez à la page d'accueil
            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
          </a>
        </div>
      </form>
    </div>
  </div>
</div>



@endsection

resources/views/classrooms/show.blade.php
@extends('layouts.menu-dashboard-teacher')

@section('content')


<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<!--main content start-->
<section id="main-content">
  <section class="wrapper site-min-height">
    <!-- page start-->
    <div class="chat-room mt">
      <aside class="mid-side">
        <div class="chat-room-head">
          <h3>Chat Room: Support</h3>
          <form action="#" class="pull-right position">
            <input type="text" placeholder="Search" class="form-control search-btn ">
          </form>
        </div>
        <div class="group-rom">
          <div class="first-part odd">Sam Soffes</div>
          <div class="second-part">Hi Mark, have a minute?</div>
          <div class="third-part">12:30</div>
        </div>
        <div class="group-rom">
          <div class="first-part">Mark Simmons</div>
          <div class="second-part">Of course Sam, what you need?</div>
          <div class="third-part">12:31</div>
        </div>
        <div class="group-rom">
          <div class="first-part odd">Sam Soffes</div>
          <div class="second-part">I want you examine the new product</div>
          <div class="third-part">12:32</div>
        </div>
        <div class="group-rom">
          <div class="first-part">Mark Simmons</div>
          <div class="second-part">Ok, send me the pic</div>
          <div class="third-part">12:32</div>
        </div>
        <div class="group-rom">
          <div class="first-part odd">Sam Soffes</div>
          <div class="second-part">
            <a href="#">product.jpg</a> <span class="text-muted">35.4KB</span>
            <p><img class="img-responsive" src="img/product.jpg" alt=""></p>
          </div>
          <div class="third-part">12:32</div>
        </div>
        <div class="group-rom">
          <div class="first-part">Mark Simmons</div>
          <div class="second-part">Fantastic job, love it :)</div>
          <div class="third-part">12:32</div>
        </div>
        <div class="group-rom last-group">
          <div class="first-part odd">Sam Soffes</div>
          <div class="second-part">Thanks!!</div>
          <div class="third-part">12:33</div>
        </div>
        <footer>
          <div class="chat-txt">
            <input type="text" class="form-control">
          </div>
          <div class="btn-group hidden-sm hidden-xs">
            <button type="button" class="btn btn-white"><i class="fa fa-meh-o"></i></button>
            <button type="button" class="btn btn-white"><i class=" fa fa-paperclip"></i></button>
          </div>
          <button class="btn btn-theme">Send</button>
        </footer>
      </aside>
      <aside class="right-side">
        <div class="user-head">
          <a href="#" class="chat-tools btn-theme"><i class="fa fa-cog"></i> </a>
          <a href="#" class="chat-tools btn-theme03"><i class="fa fa-key"></i> </a>
        </div>
        <div class="invite-row">
          <h4 class="pull-left">Team Members</h4>
          <a href="#" class="btn btn-theme04 pull-right">+ Invite</a>
        </div>
        <ul class="chat-available-user">
          <li>
            <a href="chat_room.html">
              <img class="img-circle" src="img/friends/fr-02.jpg" width="32">
              Paul Brown
              <span class="text-muted">1h:02m</span>
              </a>
          </li>
          <li>
            <a href="chat_room.html">
              <img class="img-circle" src="img/friends/fr-05.jpg" width="32">
              David Duncan
              <span class="text-muted">1h:08m</span>
              </a>
          </li>
          <li>
            <a href="chat_room.html">
              <img class="img-circle" src="img/friends/fr-07.jpg" width="32">
              Laura Smith
              <span class="text-muted">1h:10m</span>
              </a>
          </li>
          <li>
            <a href="chat_room.html">
              <img class="img-circle" src="img/friends/fr-08.jpg" width="32">
              Julia Schultz
              <span class="text-muted">3h:00m</span>
              </a>
          </li>
          <li>
            <a href="chat_room.html">
              <img class="img-circle" src="img/friends/fr-01.jpg" width="32">
              Frank Arias
              <span class="text-muted">4h:22m</span>
              </a>
          </li>
        </ul>
      </aside>
    </div>
    <!-- page end-->
  </section>
  <!-- /wrapper -->
</section>
<!-- /MAIN CONTENT -->
<!--main content end-->



@endsection