routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Notifications\Newinfo;
use App\Notifications\Newslack;

Route::get('/slack', function () {



$user = App\User::first();



$user->notify(new Newslack());



   echo "Juste une notif de oschool paths";



});

Route::get('/email', function () {

$user = App\User::first();

$user->notify(new Newinfo("A new user has visited on your application."));

   return view('homepage');

})->name('email');



Route::get('/import', 'ImportController@getImport')->name('import');
Route::post('/import_parse', 'ImportController@parseImport')->name('import_parse');
Route::post('/import_process', 'ImportController@processImport')->name('import_process');


Route::get('/', 'HomeController@racine')->name('accueil');

Route::get('/paypalstatus', 'HomeController@dashboard');



/*route pour la recherche avec ajax des users*/

Route::get('/live_search', 'LiveSearch@index');
Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');


Route::post('/merci', function () {
    return view('merci');
});

Route::post('paypal', 'PaymentController@payWithpaypal')->name('payWithpaypal');
Route::get('status', 'PaymentController@getPaymentStatus')->name('status');



Route::get('/castaing', function () {
    return view('formations.template-castaing');
});

Route::get('/cefiat', function () {
    return view('formations.template-cefiat');
});

Route::get('/esma', function () {
    return view('formations.template-esma');
});

Route::get('/etep', function () {
    return view('formations.template-etep');
});

Route::get('/epcci', function () {
    return view('formations.template-epcci');
});

Route::get('/esatic', function () {
    return view('formations.template-esatic');
});

Route::get('/ensit', function () {
    return view('formations.template-ensit');
});






Route::get('/online', function () {
    return view('online');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
Route::get('register', function () {
    return view('accueil');
});  */


Route::get('/classrooms', 'HomeController@classrooms');

Route::get('/default', 'UserController@default');

Route::get('/admin', 'AdminController@admin')
    ->middleware('is_admin')
    ->name('admin');

Route::get('/teacher', 'TeacherController@teacher')
    ->middleware('is_teacher')
    ->name('teacher');

Route::get('/partner', 'PartnerController@partner')
    ->middleware('is_partner')
    ->name('partner');


Route::resource('users','UserController');

Route::resource('emails','EmailController');

Route::resource('etatprogressions','EtatprogressionController');

Route::resource('classrooms','ClassroomController');

Route::resource('progressions','ProgressionController');

Route::resource('achats','AchatController');

Route::resource('offers','OfferController');

Route::resource('characteristics','CharacteristicController');

Route::post('/envoi', 'AchatController@envoi')->name('envoi');

Route::post('/envoiRenew', 'AchatController@envoiRenew');

Route::post('renew', 'AchatController@renew');

Route::post('/progression', 'ProgressionController@progression')->name('progression');

Route::post('/formation', 'FormationController@formation')->name('formation');

Route::post('/notify', 'AchatController@notify')->name('notify');

/*
route pour les sessions ou classrooms
*/

Route::get('/valider/{etatprogression}', 'EtatprogressionController@valider')->name('valider');

Route::get('/programme', 'ProgressionController@programme')->name('programme');

Route::get('/progression/{user}', 'ProgressionController@voir')->name('progression');

Route::resource('formations','FormationController');

Route::get('/formation/{slug}', 'FormationController@showSlug')->name('formation.slug');

Route::get('/category/{slug}', 'CategoryController@showSlug')->name('category.slug');

Route::resource('partners','PartnerController');

Route::resource('languages','LanguageController');

Route::resource('prerequisites','PrerequisiteController');

Route::resource('categories','CategoryController');

Route::resource('guides','GuideController');

Route::resource('guideprojets','GuideprojetController');

Route::get('/projects/{formation}', 'FormationController@projects')->name('projects');

Route::post('/inscription', 'UserController@inscription')->name('inscription');

Route::get('/inscrire/{user}', 'UserController@inscrire')->name('inscrire');

Route::get('/mes-etudiants', 'UserController@mesEtudiants')->name('mes-etudiants');

Route::get('/devweb', function () {
    return view('formations.parcours-dev-web');
})->name('devweb');

Route::get('/devweb2', function () {
    return view('formations.parcours-dev-web2');
})->name('devweb2');

Route::get('/facebook-marketing', function () {
    return view('formations.parcours-facebook-marketing');
})->name('facebook-marketing');

Route::get('/webdesign', function () {
    return view('formations.web-design');
})->name('web-design');

Route::get('/trading', function () {
    return view('formations.trading');
})->name('trading');

Route::get('/frontend', function () {
    return view('formations.front-end');
})->name('front-end');

Route::get('/devmobile', function () {
    return view('formations.dev-mobile');
})->name('dev-mobile');

Route::get('/devmobile', function () {
    return view('formations.dev-mobile');
})->name('dev-mobile');

Route::get('/community-management', function () {
    return view('formations.parcours-community-management');
})->name('community-management');

Route::get('/blog', function () {
    return view('formations.blog');
})->name('blog');

Route::get('/jeuxvideos', function () {
    return view('formations.parcours-jv');
})->name('jeux-videos');

Route::get('/android', function () {
    return view('formations.parcours-android');
})->name('android');

Route::get('/after-effects', function () {
    return view('formations.after-effects');
})->name('android');
Route::get('/anglais', function () {
    return view('formations.parcours-anglais');
})->name('anglais');

Route::get('/photoshop', function () {
    return view('formations.parcours-photoshop');
})->name('photoshop');

Route::get('/after-effects', function () {
    return view('formations.parcours-after-effects');
})->name('photoshop');

Route::get('/kali-linux', function () {
    return view('formations.parcours-kali-linux');
})->name('kali-linux');

Route::get('/python', function () {
    return view('formations.python');
})->name('python');

Route::get('/cours', function () {
    return view('formations.cours');
})->name('cours');

Route::get('/ecoleprog', function () {
    return view('formations.ecoleprog');
});

Route::get('/ecolemarketing', function () {
    return view('formations.ecolemarketing');
});

Route::get('/ecolelang', function () {
    return view('formations.ecolelang');
});

Route::get('/ecolebusiness', function () {
    return view('formations.ecolebusiness');
});

Route::get('/ecoleai', function () {
    return view('formations.ecoleai');
});

Route::get('/ecoledatascience', function () {
    return view('formations.ecoledatascience');
});

//voir facturation pour les teachers

Route::get('/factures', 'UserController@factures');

Route::post('/moisFactures', 'UserController@moisFactures');

Route::get('/settings', 'UserController@settings');

//voir facturation pour les admins

Route::get('/paiements', 'UserController@paiements')->name('paiements');

Route::post('/moisPaiements', 'UserController@moisPaiements');

Route::post('/formationpaiement', 'FormationController@formationpaiement')->name('paiement-par-formation');

//voir les sessions mensuelles des profs pour les admins

Route::get('/rapportProf', 'UserController@rapportProf');

Route::post('/rapportMoisProf', 'UserController@rapportMoisProf');


Route::get('/documentsTeacher', 'UserController@documentsTeacher')->name('documentsTeacher');

Route::get('/documentsStudent', 'UserController@documentsStudent')->name('documentsStudent');

Route::resource('projets','ProjetController');

Route::resource('etatprojets','EtatprojetController');

Route::resource('supportformations','SupportformationController');

Route::resource('achats','AchatController');

Route::post('/ajout-achat', 'AchatController@achat')->name('ajout-achat');

/* pour les entreprises*/

Route::get('/entreprise', function () {
    return view('formations.entreprise');
});

Route::get('/entreprise2', function () {
    return view('formations.entreprise2');
});


//pour retrouver la page profil user

Route::get('/dashboard-teacher', 'HomeController@dashboardT')->name('dashboard');

Route::get('/dashboard-admin', 'HomeController@dashboardA')->name('dashboard');

Route::get('/dashboard-default', 'HomeController@dashboard')->name('dashboard');

//pour mettre à jour le statut des abonnés

Route::get('/statutCheck', 'UserController@statutCheck')->name('statutCheck');

app/Offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    protected $fillable = ['name', 'amount'];

    public function characteristics()
    {
      return $this->belongsToMany('App\Characteristic');
    }

    public function formations()
    {
        return $this->belongsToMany('App\Formation');
    }

    public function own($characteristicId)
   {
       return $this->characteristics()->where('characteristic_id', $characteristicId)->count() > 0;
   }
}

app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use App\Offer;
use App\Characteristic;
use Auth;
use Illuminate\Http\Request;

class OfferController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->isAdmin()) {
          $offers = Offer::orderby('id','asc')->paginate(30);
          return view('offers.index', ['offers' => $offers]);
        }
        else {
          return redirect('home');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $characteristics = Characteristic::orderby('id','asc')->paginate(30);
        return view('offers.create', ['characteristics' => $characteristics]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $offer = Offer::create($request->all()); 


        $characteristics = $request->characteristic_id;

        foreach ($characteristics as $characteristic) {
          $characteristic_id = Characteristic::find($characteristic);
          $offer->characteristics()->attach($characteristic_id);
        }
        return redirect('home')->with('status', 'L\'offre a bien été créée !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function show(Offer $offer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function edit(Offer $offer)
    {
      $characteristics = Characteristic::orderby('id','asc')->paginate(30);
      return view('offers.edit', ['characteristics' => $characteristics, 'offer' => $offer]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Offer $offer)
    {
        $offer->update($request->all());
        $characteristics = $request->characteristic_id;

        foreach ($characteristics as $characteristic) {
          $characteristic_id = Characteristic::find($characteristic);
          $offer->characteristics()->sync($characteristic_id, false);
        }

        return redirect('offers')->with('status', 'Modifications apportées' );

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Offer $offer)
    {
      $offer->delete();
      return redirect('offers')->with('status', 'Offre supprimée de la base de données' );
    }
}

resources/views/offers/create.blade.php
@extends('layouts.menu-login')
@section('title', 'Ajouter une offre d\'achat')

@section('content')


<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
      <div class="login100-pic js-tilt" data-tilt>
        <img style="display: block;margin-left: auto;margin-right: auto;width: 25%;" src="/formcreate/images/img-01.png" alt="IMG">
      </div>

      <form method="post" enctype="multipart/form-data" action="{{ route('offers.store') }}" class="login100-form validate-form">
        <span class="login100-form-title">
          Ajouter une offre d'achat
        </span>
        {{ csrf_field() }}



        <div class="wrap-input100 validate-input">
          <input class="input100" value="" type="text" name="name" placeholder="Nom de l'offre" required>
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-laptop" aria-hidden="true"></i>
          </span>
        </div>

        <div class="wrap-input100">
          <input class="input100" value="" type="number" name="amount" placeholder="Prix de l'offre (par mois)">
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-laptop" aria-hidden="true"></i>
          </span>
        </div>

        <label for=""> <strong>Caractéristiques de l'offre</strong> </label>
        <select id="my-select3" name="characteristic_id[]" multiple="multiple">
          @foreach($characteristics as $characteristic)
          <option value="{{$characteristic->id}}">{{$characteristic->description}}</option>
          @endforeach
        </select>


        <div class="container-login100-form-btn">
          <button class="login100-form-btn">
            Ajouter le parcours
          </button>
        </div>


        <div class="text-center p-t-136">
          <a class="txt2" href="{{url('home')}}">
            Allez à la page d'accueil
            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
          </a>
        </div>
      </form>
    </div>
  </div>
</div>



@endsection

resources/views/offers/edit.blade.php
@extends('layouts.menu-login')
@section('title', 'Modifier une offre')

@section('content')


<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
      <div class="login100-pic js-tilt" data-tilt>
        <img style="display: block;margin-left: auto;margin-right: auto;width: 25%;" src="/formcreate/images/img-01.png" alt="IMG">
      </div>

      <form method="post" enctype="multipart/form-data" action="{{ url('offers', $offer) }}" class="login100-form validate-form">
        <span class="login100-form-title">
          Modifier l'offre: {{$offer->name}}
        </span>
        {{ csrf_field() }}
        {{ method_field('patch') }}



        <div class="wrap-input100 validate-input">
          <input class="input100" value="{{$offer->name}}" type="text" name="name" placeholder="Nom de l'offre" required>
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-laptop" aria-hidden="true"></i>
          </span>
        </div>

        <div class="wrap-input100">
          <input class="input100" value="{{$offer->amount}}" type="number" name="amount" placeholder="Prix de l'offre (par mois)">
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-laptop" aria-hidden="true"></i>
          </span>
        </div>

        <label for=""> <strong>Caractéristiques de l'offre</strong> </label>
        <select id="my-select3" name="characteristic_id[]" multiple="multiple">
          @if(count($offer->characteristics))
          @foreach($offer->characteristics as $characteristic)
          <option selected value="{{$characteristic->id}}">{{$characteristic->description}}</option>
          @endforeach
          @endif
          @foreach($characteristics as $characteristic)
            @if(!$offer->own($characteristic->id))
            <option value="{{$characteristic->id}}">{{$characteristic->description}}</option>
            @endif
          @endforeach

        </select>


        <div class="container-login100-form-btn">
          <button class="login100-form-btn">
            Modifier l'offre
          </button>
        </div>


        <div class="text-center p-t-136">
          <a class="txt2" href="{{url('home')}}">
            Allez à la page d'accueil
            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
          </a>
        </div>
      </form>
    </div>
  </div>
</div>



@endsection

resources/views/offers/index.blade.php
@extends((Auth::user()->type4 == "partner") ? "layouts.menu-dashboard-partner" : "layouts.menu-dashboard-admin")

@section('content')



<style media="screen">


/*! CSS Used from: https://egghead.io/webpack/global-styles-245ef06590e9cc433ec1.css ; media=screen */
@media screen{
a{background-color:transparent;-webkit-text-decoration-skip:objects;}
a:active,a:hover{outline-width:0;}
img{border-style:none;}
*,:after,:before{box-sizing:inherit;}
a{color:#4786ff;}
.br3{border-radius:.5rem;}
.br-pill{border-radius:9999px;}
.br--top{border-bottom-right-radius:0;}
.br--top{border-bottom-left-radius:0;}
a,div,h2,h3{box-sizing:border-box;}
.db{display:block;}
.dib{display:inline-block;}
.sans-serif{font-family:-apple-system,BlinkMacSystemFont,avenir next,avenir,helvetica,helvetica neue,ubuntu,roboto,noto,segoe ui,arial,sans-serif;}
.fw4{font-weight:400;}
.fw5{font-weight:500;}
.h-100{height:100%;}
.pointer:hover{cursor:pointer;}
img{max-width:100%;}
.lh-solid{line-height:1;}
.lh-title{line-height:1.25;}
.lh-copy{line-height:1.5;}
.o-70{opacity:.7;}
.o-60{opacity:.6;}
.overflow-hidden{overflow:hidden;}
.relative{position:relative;}
.pb3{padding-bottom:1rem;}
.pt2{padding-top:.5rem;}
.pt4{padding-top:2rem;}
.pv3{padding-top:1rem;padding-bottom:1rem;}
.ph3{padding-left:1rem;padding-right:1rem;}
.ph4{padding-left:2rem;padding-right:2rem;}
.ma0{margin:0;}
.ml2{margin-left:.5rem;}
.mt1{margin-top:.25rem;}
.mt2{margin-top:.5rem;}
.mh1{margin-left:.25rem;margin-right:.25rem;}
.tl{text-align:left;}
.tc{text-align:center;}
.no-underline{text-decoration:none;}
.ttu{text-transform:uppercase;}
.f6{font-size:.875rem;}
.w-100{width:100%;}
.z-1{z-index:1;}
.flex{display:flex;}
.flex-column{flex-direction:column;}
.items-center{align-items:center;}
.self-center{align-self:center;}
.justify-center{justify-content:center;}
.justify-between{justify-content:space-between;}
.flex-grow-1{flex-grow:1;}
.flex-shrink-0{flex-shrink:0;}
.black-90{color:rgba(0,0,0,.9);background: white;}
.black-60{color:rgba(0,0,0,.6);}
.black{color:#000;}
.base-secondary{color:#141618;}
.dark-blue{color:#344055;}
.bg-white{background-color:#fff;}
@media screen and (min-width:40em){
.ph3-ns{padding-left:1rem;padding-right:1rem;}
}
@media screen and (min-width:40em) and (max-width:62em){
.w-50-m{width:50%;}
}
@media screen and (min-width:62em){
.w-third-l{width:33.33333%;}
}
::-moz-selection{color:#fff;background:#316aff;}
::selection{color:#fff;background:#316aff;}
.eh-shadow-1{box-shadow:0 5px 30px -15px rgba(0,0,0,.2);}
}
/*! CSS Used from: Embedded */
.css-quva1q{border-radius:5px;}
/*! CSS Used from: Embedded */
.css-imtqqp{height:500px;}
/*! CSS Used from: Embedded */
.css-135bq0n{height:270px;}
/*! CSS Used from: Embedded */
.css-14p7nc1{height:270px;border-radius:10px 10px 0 0;}
@media (min-width:545px){
.css-14p7nc1{height:270px;}
}
/*! CSS Used from: Embedded */
.css-19yvy3u{max-width:262px;padding:0 16px;width:100%;}
@media (min-width:545px){
.css-19yvy3u{max-width:262px;}
}
/*! CSS Used from: Embedded */
.css-128nlh6{font-size:13px;}
/*! CSS Used from: Embedded */
.css-73nay0{height:100px;}
/*! CSS Used from: Embedded */
.css-hxrs45{line-height:1.25;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;font-size:22px;max-height:85px;}
@media (min-width:545px){
.css-hxrs45{font-size:22px;max-height:85px;}
}
/*! CSS Used from: Embedded */
.css-1eu6dtl{padding-bottom:0;border-radius:none;overflow:visible;}
/*! CSS Used from: Embedded */
.css-1i4zz36{width:35px;height:35px;}
/*! CSS Used from: Embedded */
.css-l8qto0{font-size:15px;}
/*! CSS Used from: Embedded */
.css-1qxtz39{font-size:12px;}
/*! CSS Used from: Embedded */
.css-1n42eci{-webkit-flex-basis:4.5em;-ms-flex-preferred-size:4.5em;flex-basis:4.5em;-webkit-flex-direction:row-reverse;-ms-flex-direction:row-reverse;flex-direction:row-reverse;}
/*! CSS Used from: Embedded */
.__react_component_tooltip{border-radius:3px;display:inline-block;font-size:13px;left:-999em;opacity:0;padding:8px 21px;position:fixed;pointer-events:none;transition:opacity 0.3s ease-out;top:-999em;visibility:hidden;z-index:999;}
.__react_component_tooltip:before,.__react_component_tooltip:after{content:"";width:0;height:0;position:absolute;}
.__react_component_tooltip.type-dark{color:#fff;background-color:#222;}
.__react_component_tooltip.type-dark.place-top:after{border-top-color:#222;border-top-style:solid;border-top-width:6px;}
.__react_component_tooltip.place-top{margin-top:-10px;}
.__react_component_tooltip.place-top:before{border-left:10px solid transparent;border-right:10px solid transparent;bottom:-8px;left:50%;margin-left:-10px;}
.__react_component_tooltip.place-top:after{border-left:8px solid transparent;border-right:8px solid transparent;bottom:-6px;left:50%;margin-left:-8px;}

</style>


<!-- **********************************************************************************************************************************************************
  MAIN CONTENT
  *********************************************************************************************************************************************************** -->
<!--main content start-->
<section id="main-content">
<section class="wrapper">
  <!-- page start-->

  <h3><i class="fa fa-angle-right"></i> Liste des formations en collaboration avec Oschool</h3>
  <div class="row mt">

    <div class="col-sm-12">



@if(Auth::user()->type3 == "admin")

@foreach($offers as $offer)

<div class="
        pv3 ph3-ns w-third-l w-50-m w-100 dib
        css-0
      ">
<div class="
        flex flex-grow-1 justify-between flex-column black-90


      ">
    <div class="
          flex flex-grow-1 flex-column justify-between pointer relative tc
          css-imtqqp
        ">
      <div class="
          flex flex-column flex-grow-1 w-100 flex-shrink-0
          css-135bq0n
        ">
        <div class="flex flex-column relative tc pt4">
          <div class="
                  w-100 flex items-center justify-center overflow-hidden br--top br3
                  css-14p7nc1
                ">
            <div class="
                    self-center flex-shrink-0 flex items-center
                    css-19yvy3u
                  "><img src="http://res.publicdomainfiles.com/pdf_view/2/13489777212478.png"
                alt="illustration for GraphQL Data in React with Apollo Client" class="w-100 h-100"></div>
          </div>

          <div class="
              flex flex-shrink-0 items-center w-100 overfow-hidden mt2
              css-73nay0
            ">
            <h3 class="
              tc sans-serif fw5 black-90 no-underline ma0 overflow-hidden w-100 ph4
              css-hxrs45
            "><a href="#">{{$offer->name}}</a></h3>
          </div>
        </div>
      </div>
      <div class="
        relative
        css-1eu6dtl
      ">
        <div class="flex items-center ph3 pb3 pt2">
          <div class="flex-grow-1 flex items-center"><a href="{{ route('offers.edit', $offer) }}"><img src="https://1001freedownloads.s3.amazonaws.com/vector/thumb//Anonymous_Pencil_icon.png" alt="Nik Graf" title="Nik Graf" class="
                db br-pill
                css-1i4zz36
              "></a>

                  <form action="{{ route('offers.destroy', $offer) }}" method="post">
                      {{ csrf_field() }}
                      {{ method_field('delete') }}
                      <button class="fa fa-trash" type="submit"></button>
                  </form>
            <div class="ml2">
              <div class="
                  black o-70 lh-title fw4 tl
                  css-l8qto0
                ">Oschool</div>
              <div class="
                    black-60 fw4 lh-solid mt1
                    css-1qxtz39
                  ">
                <div class="lh-solid flex items-center">{{$offer->characteristics->count()}}
                  <!-- --> caractéristiques<span class="flex items-center">&nbsp;·&nbsp;
                    <!-- --23m--></span></div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

@endforeach

{{ $offers->links() }}

@endif

</div>
</div>
</section>
<!-- /wrapper -->
</section>
<!-- /MAIN CONTENT -->
<!--main content end-->

@endsection